### ISSUE TITLE
Feedback from Telegram: @nastyathy

### ISSUE THREAD

**Issue by lennczar** [near-multicall/ui#100]
## Discord or Telegram handle
Telegram: @nastyathy

## Testnet DAO address
multical-beta-test.sputnikv2.testnet

## What did you like the most?
- Best tools for support DAO
- UI and UX very good but need more time improve it in the future.
- Have sample custom card.

## What did you like the least?
- Didn't have show result detail DAO after search.
- Didn't replace url (clear error code, transactionHashes) after redirect page.
- Didn't have message notification for user when search and create.
- Didn't disable button Propose on when invalid card (https://ibb.co/WKFH4WY).
- Sign out by click user name.
- UI menu radio App | Dao very bad. Should make menu.

## What was the most complicated?
- Must read the tutorial somewhere else
- Some value of fields Contract address, Function name, Function arguments very hard for end user. Consider change input fields by dropdown or suggestion.
- Search field near user name very small.

## Is there any feature that you wish to see in the future?
- Should high light card selected and card invalid.
- Should edit card directly instead of editing in tab Edit.
- Add notification message.
- Make sample detail of custom card such as Mint USDC, USDC transfer trick ...
- Support custom card data backup.
- Should add tutorial in web app or use library introjs (https://introjs.com/)

## How did you like the DAO setup tutorial?
**great**
## How did you like the multicall tutorial?
**great**
### "The workflow was clear."
**agree**

### "Everything worked as expected."
**agree**

### "It was fun."
**agree**

### "The UI was visually pleasing."
**neutral**
I suggest above.

### "I would use multicall for my own DAO."
**agree**
- Creating is very intuitive.
- Very fast.
- Have sample custom card

## All in all, how would you rate multicall?
4 Stars

## Is there anything else, that you would like to comment on?

https://airtable.com/app9YvmKASJgAJaNI/tblxsjEdbnT3mELHV/recurgVXEyNfWpOMi

**Comment by lennczar** [comment]
**Thank you for the feedback, we will further discuss it here:**
- [duplicate] #57
- [duplicate] #81 
- [duplicate] #76 
- (add highlighting to invalid cards) #88
- (use introjs for tutorial) #74

**Comment by mohamedalichelbi** [comment]
> * Didn't disable button Propose on when invalid card (https://ibb.co/WKFH4WY).
created #101
