### ISSUE TITLE
Disable multicall propose button on card errors

### ISSUE THREAD

**Issue by mohamedalichelbi** [near-multicall/ui#101]
**Describe the bug**
On export tab we disable the multicall propose button on any errors to prevent users from submitting invalid proposals.
However the button isn't disabled when a card has input validation errors.
<img width="931" alt="image" src="https://user-images.githubusercontent.com/28174037/168489027-bf74e628-e0b9-4c67-baf1-dd5a8cf343c3.png">

**To Reproduce**
1. Go to https://multicall.app/
2. Sign in and choose a DAO that has a multicall instance
3. Drag a custom card in. Don't fill any required input field
4. go to export tab. See how input validation errors are reported
5. See propose button still green and clickable

**Comment by lennczar** [comment]
Has been implemented, but i would suggest adding a "i know what i do" button to bypass this behavior
