### ISSUE TITLE
Uncaught TypeError upon entering Dao page

### ISSUE THREAD

**Issue by yukamend** [near-multicall/ui#109]
**Describe the bug**
Upon entering the Dao page, we get an uncaught error: "Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'policy')" in the console. This happens both logged in and logged out.

**To Reproduce**
1. Go to multicall.app or local
2. Click on Dao next to App
3. See error in console. Pop-Up when local

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/90453245/170712922-9b1a1fc9-1551-41db-8bd8-e5c0a6128a8d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 101.0.4951.67

**Comment by lennczar** [comment]
`.finally` should have been `.then`, because `.then` will actually not happen when an error was caught before, `.finally` will execute either way.
