### ISSUE TITLE
Support jobs

### ISSUE THREAD

**Issue by lennczar** [near-multicall/ui#11]
Jobs are multicalls that can be scheduled to execute at a later time, or recurrently. The multicall contract already supports this.

The implement the new feature in the UI,
1. the UI must have an option to insert a planned execution date, and weather it should recur. (typically done via crontab expressions, but other forms of input are welcome)
2. the way the UI will need to call a different contract function (`jobs_add` instead of `call`).
3. the user will need to pay a DAO specific bond.

**Comment by mohamedalichelbi** [comment]
Jobs have the following attributes:
```js
    croncat_hash: string; // (display)
    creator: string; // job creator (display)
    bond: string; // string encoded u128 number (do not display) 
    cadence: string; // crontab expression needed for croncat ( * see below for display info)
    trigger_gas: string; // string encoded u64 number (display)
    croncat_budget: string; // string encoded u128 number (do not display)
    start_at: string; // string encoded u64 number ( * see below for display info)
    run_count: number; // (display, used to tell if the progress of the job execution)
    is_active: boolean; // (display)
    multicalls: MulticallArgs[]; // (display as JSON, can be expanded or retracted. Retracted by default).
```
**\* Display info for `cadence` & `start_at`:** both attributes hold the same piece of information, which is the execution date. This should be displayed as Date + time to the user.

**Comment by Rin-Akaia-eth** [comment]
TODO:
- [ ] Render empty objects in data inspector as "`{}`"
