### ISSUE TITLE
Reload Error in console

### ISSUE THREAD

**Issue by yukamend** [near-multicall/ui#117]
**Describe the bug**
Error in the console when reloading the page, while having an card with arguments open

**To Reproduce**
1. Create Custom Card
2. Input args
3. Reload page

**Expected behavior**
No error.

**Screenshots**
![image](https://user-images.githubusercontent.com/90453245/173091393-21eaf7d0-ca07-400a-ae0f-e783874f2155.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 102.0.5005.115

**Comment by mohamedalichelbi** [comment]
It's coming form the XDEFI wallet extension you have on ur browser
