### ISSUE TITLE
Facilitate Dapp login with multicall / DAO accounts

### ISSUE THREAD

**Issue by mohamedalichelbi** [near-multicall/ui#147]
**Is your feature request related to a problem? Please describe.**
Although many efforts were made to facilitate interacting with Dapps using a DAO (function call templates, Near-multicall...), DAO users have no access to info generated by Dapp interfaces, like current DeFi positions, pending unclaimed rewards...
This feature request aims to fix that by allowing users to login with DAO/multicall accounts into Dapps.

**Describe the solution you'd like**
A "Dapp login" button on the sidebar:
1. User clicks the button which opens a pop-up
2. User is asked whether he wants to login using multicall contract or DAO.
3. User is asked to:
    1. Go to the Dapp website he wants to use
    2. Logout of his current wallet
    4. Copy the Dapp URL
    5. Paste  the URL in an input field in the popup
3. We generate a Login URL, similar to `https://app.pembrock.finance/?account_id=multicall.near&public_key=ed25519%3ADEaoD65LomNHAMzhNZva15LC85ntwBHdcTbCnZRXciZH&all_keys=ed25519%3A9jeqkc8ybv7aYSA7uLNFUEn8cgKo759yue4771bBWsSr` (notice the `account_id` URL parameter) and display 2 bttons: one opens the URL in a new tab to login as DAO, the other to login as multicall

Note: We just need to change `account_id` URL param, other things related to Key can be hardcoded to some constant placeholder.

**Describe alternatives you've considered**
A limitation to this approach is that users can't use UI features that require signing a transaction. This can be solved in the future by implementing our own Wallet that automatically converts those transactions to DAO proposals

**Additional context**
None

**Comment by Rin-Akaia-eth** [comment]
Additional requirements:
- URL validation
