### ISSUE TITLE
Storage standard cards

### ISSUE THREAD

**Issue by mohamedalichelbi** [near-multicall/ui#149]
**Is your feature request related to a problem? Please describe.**
Support [storage standard](https://nomicon.io/Standards/StorageManagement) methods, especially `storage_deposit()` and `storage_withdraw()`. PR #137 adds a Storage deposit card for FT tokens but we can generalize it.

**Describe the solution you'd like**
2 deliverables:
- Storage standard TS class.
- Cards for storage methods

**Describe alternatives you've considered**

**Additional context**

**Comment by lennczar** [comment]
implemented in #164
```
* added storage_withdraw card
* added storage_withdraw and storage_unregister
* fix: storage_deposit depo
```
