### ISSUE TITLE
Page for multicall contract creation

### ISSUE THREAD

**Issue by mohamedalichelbi** [near-multicall/ui#15]
**Description:**
Currently we have a [multicall factory](https://github.com/near-multicall/contracts/tree/main/assembly/factory) that creates multicall instances for DAOs by calling the [create function](https://github.com/near-multicall/contracts/blob/175733b80904ef56d32de3acf213b1a19709a15b/assembly/factory/index.ts#L112)
We need UI support for this so DAOs can easily create their instances

**Proposed changes:**
a UI section / page where users can specify a DAO address (like `multicall.sputnik-dao.near`) and the UI does the following:
1. check if there's code deployed on that contract: if code exists then the DAO already has a multicall instance so show an error. If no code continue
2. check if the user can create a proposal on the target DAO
3. Compose [multicall args](https://github.com/near-multicall/contracts/blob/175733b80904ef56d32de3acf213b1a19709a15b/assembly/factory/model.ts#L5) in the background. where admin_accounts is an array with a single element: the DAO address. croncat_manager will be a constant hardcoded in the UI and job_bond is equal to the bond used in the DAO for proposal creation.
4. Allow the user to click a button. By clicking the button a function call proposal is created on the target DAO to create a multicall instance.

**Comment by lennczar** [comment]
Ideally this should happen on the DAO page, when the user is trying to find a non existent multicall instance.
This could also be within an error message, that shows up when the user tries to propose on a DAO, that does not have a multicall instance (goes with #16)

**Comment by lennczar** [comment]
The current logic flow behind the dao page loading mechanism looks like the following:

![dao-page-flow](https://user-images.githubusercontent.com/42617542/162085053-22ee2d9e-6c98-4f45-a9bc-ed43ee061b61.png)

**Comment by lennczar** [comment]
Suggested new logic flow

![dao-page-flow-new](https://user-images.githubusercontent.com/42617542/162086864-e5080064-96e1-480b-bbb0-ad975e050ab9.png)
