### ISSUE TITLE
Gas exceeded on automatically paid storage deposit

### ISSUE THREAD

**Issue by mohamedalichelbi** [near-multicall/ui#150]
**Describe the bug**
When trying to attach a whitelisted token to a multicall proposal, where the multicall contract doesn't have storage deposit on it yet, our UI makes a batch proposal that 1) pays for storage and 2) executes multicall using `ft_transfer_call`.
However, this might lead to proposals being unable to be approved due to gas errors. We currently reserve `270 Tgas` per default for multicall, additionally we need `5 tgas` for the storage deposit. Which only leaves the SputnikDAO contract with a maximum of `25 Tgas` to execute its governance logic, which isn't enough in [some cases
](https://explorer.testnet.near.org/transactions/G2io57rKZaXEESQXHU2FePja2GahSnZymQSaKNDTxBf8)
**To Reproduce**
1. Find a Fungible token where multicall doesn't have storage, and whitelist it.
2. Make a multicall proposal that attaches that token on export page.
3. Observe how the DAO proposal has 2 actions: `storage_deposit` and `ft_transfer_call`.
4. Try to vote approve the proposal, the vote that will lead to execution will always fail for some DAOs (idk  why?)

**Expected behavior**
Proposal should be able to execute

**Screenshots**
none

**Additional context**
This was tested on a Sputnik V2 DAO and was successful. It failed on some Sputnik V3 DAOs so they might be more gas hungry.

**Comment by lennczar** [comment]
What are possible solution?
Lower the 270Tgas limit (for all / only certain scenarios)
Make it a Job

**Comment by mohamedalichelbi** [comment]
> What are possible solution? Lower the 270Tgas limit (for all / only certain scenarios)
Depends on how much extra Gas is needed. If it's less than 1 Tgas, then I'll lower the `5 Tgas` from storage deposit to 4.5 or 4. Otherwise we lower the default `270Tgas`, for all scenarios. This is because the calculation is done after the user clicks on the "propose" button, so I think gas values should stay the same in all scenarios
