### ISSUE TITLE
Verify user can make proposal

### ISSUE THREAD

**Issue by mohamedalichelbi** [near-multicall/ui#16]
**Is your feature request related to a problem? Please describe.**
Our UI allows a user to specify any DAO address and make a proposal TX to it, which will fail. [SputnikDAO contracts](https://github.com/near-daos/sputnik-dao-contract/tree/main/sputnikdao2/src) have a permissioned model for who can do what on the dao, specified in the DAO policy. We also don't check existence of a multicall instance deployed in the target multicall address.

**Describe the solution you'd like**
1. Fetch policy of the target DAO, find the current user's role and verify his role actually allows him to create a proposal
2. verify existence of a multicall instance deployed for that DAO

**Describe alternatives you've considered**
Using the [Astro API](https://github.com/near-daos/astro-api-gateway) for fetching user data is also an option, but for the moment it has few issues with being up-to-date, it also introduces trusted intermediaries

**Comment by lennczar** [comment]
#18 (pr: #23) implements the following checks already:
- (Dao address is valid)
- Address refers to a sputnik dao
- The dao has a multicall instance on the correspondent address
- User has required proposal rights (`FunctionCall:AddProposal`, [more info](https://github.com/near-daos/sputnik-dao-contract#roles-and-permissions))
