### ISSUE TITLE
Make DAO more selection global

### ISSUE THREAD

**Issue by mohamedalichelbi** [near-multicall/ui#17]
**Is your feature request related to a problem? Please describe.**
Users now have to choose a DAO in 2 separate places. First, on the build page under the export tab. This determines which DAO will the multicall be proposed on. Second in the DAO page, to select what DAO to see information about.

**Describe the solution you'd like**
Would be nice if DAO selection is a more obvious and global thing, just like what account is the user signed in with. when a DAO is selected then it should be chosen for all pages. This also helps to determine whether the user is able to do something on that DAO from the beginning, see #16 

**Describe alternatives you've considered**
A possibility is to have something on the header, where a user can input a DAO address using a text field, and preferably also have autocomplete suggestions coming from a selection of DAOs provided from the Astro API for that particular user ("your DAOs"). 
It would also be nice to save DAOs that a user has used previously in his local storage and suggest them to him in the future

**Comment by lennczar** [comment]
There's a great MUI component for this. It will autocomplete to a set of selections and also accept custom values:
https://mui.com/components/autocomplete/#creatable

**Comment by lennczar** [comment]
A new file was introduced: `persistent.ts`, which serves as a navigation persistent place to store user, dao and multicall addresses. Once a better solution was found in #5, technology should adapt.
