### ISSUE TITLE
Cloned cards not validated initially

### ISSUE THREAD

**Issue by mohamedalichelbi** [near-multicall/ui#173]
**Describe the bug**
Using the new args code (on **arg-refactor** branch) When a card is cloned, the new card does not get validated till the user clicks inside (no red highlighting on the card or its field).

**To Reproduce**
1. Create any card
2. Make sure at least one field is invalid on the card
3. Clone the cord
4. See the new card (clone result) doesn't have an error on the field that's invalid on the parent card.

**Expected behavior**
Error validation should happen as soon as the card is created.

**Comment by lennczar** [comment]
fixed in #164
