### ISSUE TITLE
Multicall cards

### ISSUE THREAD

**Issue by mohamedalichelbi** [near-multicall/ui#33]
- [ ] add tokens to whitelist
- [ ] remove tokens from whitelist
- [ ] change job bond
- [ ] change croncat manager address
- [ ] add admins (this is dangerous, not sure we should expose this to users YET)
- [ ] remove admins (this is dangerous, not sure we should expose this to users YET)

**Comment by mohamedalichelbi** [comment]
IDEA: cosnider having a list of default tokens tat can be whitelisted in one go, like all top tokens (DAI, USDC, REF, wNEAR ...), make sure token contracts for those tokens are locked.

**Comment by lennczar** [comment]
DAO page takes care of this functionality
