### ISSUE TITLE
propose multicall parameter changes from DAO page

### ISSUE THREAD

**Issue by mohamedalichelbi** [near-multicall/ui#35]
**Is your feature request related to a problem? Please describe.**
Ticket #33 will support proposing changes to token whitelist, croncat manager, job bond and admins (again, changing admins is dangerous, maybe don't support from UI yet). These parameters are listed on the DAO page, it'd be nice to be able to edit these parameters and propose these changes to the DAO.

**Describe the solution you'd like**
The user can make a series of edits to these parameters on the DAO page, and at the end he should be able to propose changes using a simple DAO proposal (doesn't go through multicall, since target is the same, and we want all-or-nothing for this). The user should be able to input a proposal description and click a button to make a proposal. Things like gas and deposit can be determined by the UI and don't have to be changeable on the UI.

**Describe alternatives you've considered**

**Additional context**

**Comment by Rin-Akaia-eth** [comment]
TODO: "Copy address" button ( in popup? ) for every NEAR link rendered as `NearLink` component

**Comment by Rin-Akaia-eth** [comment]
TODO: Make font sizes in multicall config editor smaller for one step

**Comment by Rin-Akaia-eth** [comment]
TODO: Try to use default text input to solve value updates issues
