### ISSUE TITLE
support batch actions per card

### ISSUE THREAD

**Issue by mohamedalichelbi** [near-multicall/ui#36]
**Is your feature request related to a problem? Please describe.**
currently cards display 1 function call and its arguments. However the smart contract can handle multiple actions on the same target per call (batch actions). It would be nice of the UI can support this, as it would help with things like paying storage in FT transfer card, and supporting multiple transfers per token.

**Describe the solution you'd like**
Cards should support displaying multiple [actions](https://github.com/near-multicall/contracts/blob/498fba9f085d200ca0e406e9a4681a7657fbe9bd/assembly/multicall/model.ts#L5) per card. Custom card should allow users to make multiple function calls on a single target.

**Describe alternatives you've considered**

**Additional context**

**Comment by lennczar** [comment]
Swagger API documentation: https://api.app.astrodao.com/docs/#/

**Comment by lennczar** [comment]
implemented Batches in #164
