### ISSUE TITLE
FT transfer card should pay for storage

### ISSUE THREAD

**Issue by mohamedalichelbi** [near-multicall/ui#37]
**Is your feature request related to a problem? Please describe.**
FT transfers will fail if the receiver doesn't have storage balance on the token contract. We should detect this and suggest to pay it from the card.

**Describe the solution you'd like**
We can have a checkbox for each transfer action in the card ( see #36 ) to suggest paying the receiver's storage.
When the user specifies a receiver address in FT transfer card, The card should query the user's storage and if he doesn't have any then we should suggest to the user to pay the storage by checking the checkbox mentioned above.

**Describe alternatives you've considered**

**Additional context**

**Comment by lennczar** [comment]
implemented Batches in #164
