### ISSUE TITLE
add "Display PROPOSAL" and fix some features

### ISSUE THREAD

**Issue by TLGKien** [near-multicall/ui#40]
**Discord or Telegram handle**
Telegram handle: @tlgkien123 
Discord: neiknav#1259

**Is your feature request related to a problem? Please describe.**
1. The generated PROPOSAL is not displayed, quite difficult to manage when creating on one page and tracking on another

**Describe the solution you'd like**
1. Displays existing PROPOSALs and their status, so that users can manage and monitor them easily,
2. should separate icon "delete" and icon "copy". The "copy" icon is not correct, it should be changed to an icon so that users can see and immediately know it is a copy icon
3. When editing cards, add a "save" or "cancel" button

**Describe alternatives you've considered**
**Additional context**

**Comment by lennczar** [comment]
**Thank you for the feedback, we will further discuss it here:**
- Checkout multicall proposals + vote from there (addressed in #12)
- Update clone icon (addressed in #72)
