### ISSUE TITLE
Clear transactionHashes when redirect page after payment for CREATE NEW DAO

### ISSUE THREAD

**Issue by rony2818** [near-multicall/ui#42]
**Discord or Telegram handle**
Telegram handle: @RonyLe2818

**Describe the bug**
Don't clear transactionHashes after redirect page.

**To Reproduce**
1. Create new dao
2. Successful payment and redirect page
3. Browser url still show ?transactionHashes=5f5feLNxBJaTEBt7icqYuWiZfPaBwsGP2wzkzLvT5nUz#

**Expected behavior**
Replace window url by clear state value after redirect page after payment and show notification message status

**Screenshots**
<img width="790" alt="Screen Shot 2022-05-10 at 20 23 24" src="https://user-images.githubusercontent.com/11047732/167640237-49aab4ca-a141-40d9-bcbb-cab1fd5f2fba.png">

**Comment by mohamedalichelbi** [comment]
Thank you @rony2818 
Actually, this applies to multicall as well. It'll be done in #57
