### ISSUE TITLE
Click icon go to home page not working.

### ISSUE THREAD

**Issue by rony2818** [near-multicall/ui#43]
**Discord or Telegram handle**
Telegram handle: @RonyLe2818

**Describe the bug**
Click icon go to home page not working.

**To Reproduce**
1. Select any dao name at home page
2. Click Icon of page at top left
3. Not go to home page still in detail of dao

**Expected behavior**
Go to home page

**Screenshots**
<img width="1435" alt="Screen Shot 2022-05-10 at 20 46 01" src="https://user-images.githubusercontent.com/11047732/167643530-6eaaee47-239e-4c42-b422-4c6cae005412.png">

**Comment by lennczar** [comment]
@rony2818 Thank you for your afford in finding these issues, unfortunately the website testnet-v2.sputnik.fund is not part of our product. This means we can also not fix any of these issues ourselves, to have these issues fixed please post them as issues at [their GitHub repo](https://github.com/near-daos/sputnik-dao-2-ui-reference).

If you are following the LNC testers guide, please note that while we do use Sputnik DAO as a third party in our setup steps, the testing should be focus around our web app https://multicall.app
