### ISSUE TITLE
Duplicate search field DAO

### ISSUE THREAD

**Issue by rony2818** [near-multicall/ui#48]
**Discord or Telegram handle**
Telegram handle: @RonyLe2818

**Is your feature request related to a problem? Please describe.**
Duplicate UI and functions.

**Describe the solution you'd like**
Remove search DAO on top menu because it very small.

<img width="1688" alt="Screen Shot 2022-05-10 at 21 59 18" src="https://user-images.githubusercontent.com/11047732/167660156-15706ae7-5c25-4f52-bc06-0b2c7e04b8e0.png">

**Comment by lennczar** [comment]
**Thank you for the feedback, we will further discuss it here:**
- Add tooltips #73
