### ISSUE TITLE
Make state persist navigation and reload

### ISSUE THREAD

**Issue by lennczar** [near-multicall/ui#5]
The app should not clear data (remove cards) upon refresh or navigating to a different page and back.
The state could possibly e saved in `local`- or `sessionStorage` or as `cookies`. We might need to think of serialization to reduce stoarge amounts.

This issue might go hand in hand with #6

**Comment by mohamedalichelbi** [comment]
We currently reference cards by a [numerical ID](https://github.com/near-multicall/ui/blob/f3d2ff8c7bb40049f1e4659bce72e603ec89f9de/src/initial-data.js#L3). I think it's useful here to switch to a string that is more related to the Card's function (maybe: family name + '_' + card name).
Imaging following situation:
1. User saves a multicall in JSON string format
2. UI receives card updates (so card indices change in the column)
3. User tries to display the multicall => error since card indices have changed

What do u think? @lennczar

**Comment by lennczar** [comment]
The problem here is that we store the positions of the cards in the `Layout` Component. When the user navigates to a different page and back, the `Layout` component loses its state. This also happens to the global value `window.TASKS`, which serves as a reference to all `Task` Components, effectively clearing the entire layout.

What @mohamedalichelbi mentioned might be more relating to #6, saving and loading from save files. For this we should be able to infer the card type from the normalized JSON.

**Comment by lennczar** [comment]
> We currently reference cards by a [numerical ID](https://github.com/near-multicall/ui/blob/f3d2ff8c7bb40049f1e4659bce72e603ec89f9de/src/initial-data.js#L3). I think it's useful here to switch to a string that is more related to the Card's function (maybe: family name + '_' + card name).
> Imaging following situation:
> 1. User saves a multicall in JSON string format
> 2. UI receives card updates (so card indices change in the column)
> 3. User tries to display the multicall => error since card indices have changed
> 
> What do u think? @lennczar 


@mohamedalichelbi, the numeric IDs you mentioned are simple for internal use of `react-beautiful-dnd`, our drag and drop library. The don't have any effect on the final export, so unless we have a second export type, there's no need to change it

**Comment by lennczar** [comment]
## Current (partial) solution
We currently have a class defined in `src/utils/persistent.ts`, it stores important near addresses so they will persist page navigation (switching between DAO and APP page), however it will be cleared whenever the user refreshes the page (first problem). 
It also does not hold any other important information such as the multicall layout (second problem). 
The class does supply a function that will update certain components if the global near addresses are mutated, however it would be nice if this could just be an event / hook / observable. Instead of having a growing list of things to update in this file, the components that should update on "onaddresseschanged" just listen for the event / clink into the hook / observe the observable and update itself if necessary.

## What we want
The solution should
- [ ] store essential data (addresses & layout)
- [ ] persist reload & navigation
- [ ] fire an event (or similar) when a value changed

The first two items are addresses in the example code below.

## Example code from an old project of mine
#### Global variable
```js
let cookieFile;
let cookie = {
    set: (name, value) =>
        document.cookie = name + "=" + value,
    get: name => {
        var decodedCookie = decodeURIComponent(document.cookie).split(';');
  	for (let c of decodedCookie) 
  	    if (c.trim().split("=")[0] == name)
  	        return c.trim().split("=")[
            return "";
    }
}
```
#### When component is mounted (LOAD)
```js
if (!cookieFile && document.cookie != "") {
    cookieFile = {
    	name: cookie.get("initName"), 
    	data: cookie.get("grid"),
    	size: JSON.parse(cookie.get("sizing"))
   };
if (cookieFile.data != "[]")
   loadGrid(cookieFile);
```
#### Before user leaves the page (SAVE)
A snippet similar to the following can go in `src/utils/loader.ts` and replace the current beforeunload listener
```js
window.addEventListener('beforeunload', () => {
    cookie.set("grid", p.saveGrid(true));
    cookie.set("initName", initName);
    cookie.set("sizing", JSON.stringify({
        w: p.width, 
        h: p.height
    }));
});
```
