### ISSUE TITLE
Autocomplete or dropdown for Contract address and Function name

### ISSUE THREAD

**Issue by rony2818** [near-multicall/ui#50]
**Discord or Telegram handle**
Telegram handle: @RonyLe2818

**Is your feature request related to a problem? Please describe.**
- UI not friendly
- Take a lot of time.
- User must remember data and check some document to find exactly Contract address and Function name.

**Describe the solution you'd like**
- Collect metadata of Contract address and Function name.
- Change input field by dropdown or autocomplete.

<img width="412" alt="Screen Shot 2022-05-10 at 22 12 06" src="https://user-images.githubusercontent.com/11047732/167663276-e5a8f334-f718-4f47-ab6a-920d012ffd66.png">

**Comment by mohamedalichelbi** [comment]
Some of the issues raised here will be addressed in #79
