### ISSUE TITLE
Separate Function arguments to 2 fields.

### ISSUE THREAD

**Issue by rony2818** [near-multicall/ui#51]
**Discord or Telegram handle**
Telegram handle: @RonyLe2818

**Is your feature request related to a problem? Please describe.**
- Not friendly.
- Input json very hard for end user.
- User must read guild for this field.
- Difficult for validate.

**Describe the solution you'd like**
- Make 2 fields input: account id and amount

**Comment by mohamedalichelbi** [comment]
Some of the issues raised here will be addressed in #79
