### ISSUE TITLE
When creating DAO, it always show "error symbol" next to Council member textbox. After press submit it become "OK".

### ISSUE THREAD

**Issue by that83** [near-multicall/ui#54]
**Discord or Telegram handle**
Discord: that83 #0407

**Describe the bug**
When creating DAO, it always show "error symbol" next to Council member textbox. After press submit it become "OK".

**To Reproduce**
1. create new DAO
2. it always show "error symbol" next to Council member textbox
3. input a valid NEAR account. "error symbol" is still shown.

**Expected behavior**
"OK symbol" should be shown after a valid account was typed here.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lennczar** [comment]
@that83 Thank you for your afford in finding these issues, unfortunately the website testnet-v2.sputnik.fund is not part of our product. This means we can also not fix any of these issues ourselves, to have these issues fixed please post them as issues at [their GitHub repo](https://github.com/near-daos/sputnik-dao-2-ui-reference).

If you are following the LNC testers guide, please note that while we do use Sputnik DAO as a third party in our setup steps, the testing should be focus around our web app https://multicall.app/
