### ISSUE TITLE
Great job

### ISSUE THREAD

**Issue by cryptocradle1** [near-multicall/ui#55]
**Discord or Telegram handle**  
If feedback eligible for reward, we'll reach out to ask for your near wallet address 
telegram: @Icysand

**Testnet DAO address**  
Testnet DAO address(es) used during the test:
testchik.testnet

**what did you like the most?**  
I liked how easy it was to create such proposals without knowing how to code

**What did you like least?**  
I didn't like the font size on the multicall website, it was small for my eyes

**What was the most difficult?**  
I was struggling with what should do at first, then I watched the gifs in the guide then figured it out

**What did you find easy?**  
It was really easy to duplicate cards and drag and drop

**On a scale from 1 to 5 (1 = not good, 5 = really good)**  
* The instructions on DAO setup were easy to follow: 5
* The instructions on multicalls usage were easy to follow:  5

**finally, do you have some other thoughts you'd like to share?**  
it was a very smooth process. great job

**Comment by lennczar** [comment]
**Thank you for the feedback, we will further discuss it here:**
- increase accessibility #76 
- improve guidance #74
