### ISSUE TITLE
Multicall Beta Test

### ISSUE THREAD

**Issue by that83** [near-multicall/ui#56]
**Discord or Telegram handle**  
Discord: that83 #0407 

**Testnet DAO address**  
Testnet DAO address(es) used during the test: nearnear.sputnikv2.testnet

**what did you like the most?**  
I liked the idea of multi actions can be included in a proposal, and the GUI of App that helps non-developer could also create a multi-action proposal.

**What did you like least?**  
I didn't like that app don't have hints and guild messages, for example, when mouse over buttons, so I can not understand some feature at the first time.

**What was the most difficult?**  
First time came to app I did not know how to use the app. For Ex, the switch between "App" and "DAO" tab, the board Admins, Tokens, Jobs, and "+" buttons beside them.

**What did you find easy?**  
It was really easy to export to proposal in my DAO. Thank for this feature.

**On a scale from 1 to 5 (1 = not good, 5 = really good)**  
* The instructions on DAO setup were easy to follow: 4
* The instructions on multicalls usage were easy to follow: 4.5

**finally, do you have some other thoughts you'd like to share?**  
+ I think app should have more template (preset) to be used. Now have only 3 template (custom, FT transfer, Near transfer). You should add more, for Ex: NFT transfer, ...
+ User may want to clone their existing proposals so the app should allow the to import "args" of existing proposal to app, instead of creating from begining. (and the councils need this feature also, before approving an proposal they need to read it in a visual format)
+

**Comment by mohamedalichelbi** [comment]
> I didn't like that app don't have hints and guild messages

will be fixed in #73
