### ISSUE TITLE
Improve search status

### ISSUE THREAD

**Issue by bruno-le** [near-multicall/ui#65]
**Discord or Telegram handle**
Discord: letu02#5055

**Is your feature request related to a problem? Please describe.**
Didn't know status of search DAO, only show status at bottom on tab Export

**Describe the solution you'd like**
 Move search status to top of page

<img width="891" alt="Screen Shot 2022-05-11 at 11 00 13" src="https://user-images.githubusercontent.com/105336103/167773042-bfd792f4-9785-4481-946a-1f1d3e036af5.png">

**Comment by lennczar** [comment]
**Thank you for the feedback, we will further discuss it here:**
- #78
