### ISSUE TITLE
Improve performance search DAO

### ISSUE THREAD

**Issue by bruno-le** [near-multicall/ui#66]
**Discord or Telegram handle**
Discord: letu02#5055

**Is your feature request related to a problem? Please describe.**
Performance very bad after release if have many user search DAO. Call request search multiple when user input each characters.

**Describe the solution you'd like**
 Add debounce search onChange search fields.
Refer docs: https://lodash.com/docs/#debounce

<img width="1688" alt="Screen Shot 2022-05-11 at 11 01 27" src="https://user-images.githubusercontent.com/105336103/167774861-ba6ef5b0-78bd-49f8-b3ef-c47f172bcdde.png">

**Comment by lennczar** [comment]
**Thank you for the feedback, we will further discuss it here:**
- #77
