### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by NgocJena** [near-multicall/ui#71]
**Discord or Telegram handle**  
Telegram: @nooneatall09

**Testnet DAO address**  
Testnet DAO address(es) used during the test: lovelysugar.sputnikv2.testnet

**what did you like the most?**  
- The thing that impressed me the most is near-multicall tool. Instead of making multiple voting steps, Dao members now only need to confirm 1 time for each proposal. This reduces processing time and increases efficiency.
The instructions have clearly stated the steps to be able to mint usdc and usdt for DAO members. As usual, DAO members will have to agree and vote 4 times to reach the final proposal. With Near-multicall, this can be done in one vote. 

**What did you like least?**  
- Personally, I find the website colors a bit faded. The letters are mostly gray and light colors, the font size is small, because my eyes are short-sighted, so it's quite difficult to see. I hope that the letters will be bolder and clearer.

**What was the most difficult?**  
- I was struggling with Creating proposals with multicall. At first, when I didn't understand the interface and how it worked, it was difficult for me to create cards. I tried to click on the card but no success until I watch your gif tutorial. I need to drag the template card to the right place, not try to click on it. 
After understanding the functions, now I feel comfortable and quite easy to implement.

**What did you find easy?**  
I can vote yes or no easily and quickly for a proposal. if I am a DAOmember, I will find it much easier and more convenient because with a proposal I will only need to vote once. 
**_=> Quick operation, no time consuming, and saving voting fees (just pay only 1 fee)_**

**On a scale from 1 to 5 (1 = not good, 5 = really good)**  
* The instructions on DAO setup were easy to follow: 4
* The instructions on multicalls usage were easy to follow: 5

**finally, do you have some other thoughts you'd like to share?**  
![font error](https://user-images.githubusercontent.com/91360744/167810730-1a4f98bb-1f3e-4da2-ada9-a5b80fc568b1.PNG)
On my screen, "gas" and "yocto" are missing part of the text below. I have attached the picture above.

![tutorial](https://user-images.githubusercontent.com/91360744/167813915-9b1831d3-766d-4c0b-b5e9-12a905709c49.PNG)
The guide box on the right side of the screen is not proportionate. It should recede slightly to the right. I have illustrated with the image above.

![Daonameaddress](https://user-images.githubusercontent.com/91360744/167818974-e27e66a0-3dda-4c3e-9bbe-2f99063c24f5.PNG)
I see that ".sputnikv2.testnet" is already available, so I just insert DAO name in the input . After I enter the DAO name, can i copy the full DAO address. For example, next to ".sputnikv2.testnet" word will have a copy icon .After clicking on it, I will have my full DAO address. 

#

**Comment by lennczar** [comment]
**Thank you for the feedback, we will further discuss it here:**
- #76 
- #74
