### ISSUE TITLE
Improve accessibility

### ISSUE THREAD

**Issue by mohamedalichelbi** [near-multicall/ui#76]
**Is your feature request related to a problem? Please describe.**
We should increase accessibility on the website.
1. adjust colors & contrast
2. Some users complained about font size being too small. I think it's especially relevant for cards

**Describe the solution you'd like**
Adjust colors:
- On unit selector (NEAR<->yocto or gas<->Tgas) sometimes text and background have the same color (white on white). Make sure things like this don't happen by testing on different browsers (especially chrome & firefox) and different light modes (brigth, dark...)
- Increase font size, especially on cards used inside columns

**Comment by lennczar** [comment]
Additionally, rethink the design of the propose button (#84)
