### ISSUE TITLE
Debounce DAO field in wallet input

### ISSUE THREAD

**Issue by lennczar** [near-multicall/ui#77]
**Describe the bug**
The DAO wallet input is not debounced. This leads to a performance issue. 

**To Reproduce**
1. Open Network tab in web console
2. Type in the DAO wallet input

**Expected behavior**
See a single RPC request once the user has not typed for something like 500ms.

**Screenshots**
![image](https://user-images.githubusercontent.com/42617542/167911191-6a12760c-7468-43c4-b842-d3b600662376.png)

**Additional context**
Reported here #66

## Current solution
Apart from this field, other inputs on the UI need de-bouncing. To my knowledge all other (async) inputs are de-bounced, although the solution we have implemented is very temporary and messy, it requires a local variable and redundant code for every field that is de-bounced.
### Example: ft-transfer card
> We define a local variable `lastInput`, holding a timestamp of when the user last pressed a key, 400ms after we will update our data unless the user pressed another key in this time interval, then we restart the 400ms.
> See example code [here](https://github.com/near-multicall/ui/blob/9e5637467c203313715681b795d54b628d697a7e/src/families/near/transfer.js#L135)
```jsx
lastInput;

// ...

<TextInput 
    label="Token address"
    value={ addr }
    error={[ errors.addr, errors.noToken ]}
    update={ () => {
        this.updateCard();
        setTimeout(() => {
            if (new Date() - this.lastInput > 400) // <-- hard coded values :(
                this.updateFT()
        }, 500)
        this.lastInput = new Date()
    } }
/>
```
**note:** as far as I am aware for all implementations of de-bouncing we use the `lastInput` variable to just do a ctrl-shift-F (vscode) search to find all occurrences.

## Desired solution
Little to no redundant code, and easy to just apply to a new input field, ideally just give it an attribute or similar. I believe the industry standard is to use the lodash library (basically collections of utility functions), but since we don't need anything else from that library (i think), let's try de-bounce without adding the entire lodash library as a dependency.

**Comment by mohamedalichelbi** [comment]
@koussay-khelil field in question:
<img width="931" alt="image" src="https://user-images.githubusercontent.com/28174037/167939707-4e2161e5-e398-4032-8e96-cdcb77eb15ef.png">
