### ISSUE TITLE
various small improvements by gachip_1010

### ISSUE THREAD

**Issue by mohamedalichelbi** [near-multicall/ui#88]
**Is your feature request related to a problem? Please describe.**
1. When checking if a Dao has Multicall instance installed or not (Step 2,3 section b) => the same color is used for all check points. My suggestion is only the ones with cross sign is in red, the rest check points can be in green or grey. This way people will immediately know which is checked, which is not checked yet at a glance.
<img width="932" alt="image" src="https://user-images.githubusercontent.com/28174037/167932961-f77975b5-7264-4aa9-a978-af1bbf3b3730.png">

2. Text input for card title should make it more obvious that it's editable. Exp: make the field "filled". Also make that field auto-focus when clicking the "edit" icon
<img width="936" alt="image" src="https://user-images.githubusercontent.com/28174037/167934743-fc79f005-73dd-429a-85c7-a3160e39ed21.png">

3. The being-edited-card: It is too difficult to know which card is being edited when there are many cards. Let's say we have 4 cards: mint USDC, transfer USDC, mint USDT, transfer USDT. When I click edit to paste the contract address, I dont know which card I am at. I have to check the Name section (the Custom line), but as mentioned before, the Custom line is not outstanding, so it takes some time for me to figure out which card I'm editing => I suggest that there are some noticeable points that show we are editing or choosing a certain card. For ex if I choose the mint USDC card, that card would have green border, so that it's outstanding.

**Comment by lennczar** [comment]
As suggested in #100, invalid cards should also be highlighted
