### ISSUE TITLE
Title of Card is Unclear

### ISSUE THREAD

**Issue by Wabinab** [near-multicall/ui#89]
**Discord or Telegram handle**
@WabinabUknown

![image](https://user-images.githubusercontent.com/71509699/167990374-ef44fa32-29bf-4a4e-a722-c5b3204f613e.png)

**Is your feature request related to a problem? Please describe.**
I always see the **contract address** as the "Title" of the card. 

**Describe the solution you'd like**
Perhaps move it down or make it more clear as a field rather than just having a line below it. 

**Describe alternatives you've considered**
NIL

**Additional context**
NIL

**Comment by lennczar** [comment]
**Thank you for the feedback, we will further discuss it here:**
- [duplicate] #88
