### ISSUE TITLE
Cannot "Propose On"

### ISSUE THREAD

**Issue by Wabinab** [near-multicall/ui#90]
**Discord or Telegram handle**
@WabinabUknown

**Describe the bug**
Cannot click the "Propose On" button despite all as expected (because DAO address is gone for no reason)

**To Reproduce**
1. Follow this tutorial https://learnnear.club/multicall-beta-test/
2. Instead of creating a "Custom" for ft_transfer, use the `ft_transfer` card instead (and fill in as usual the fields where it supposed to go into the function arguments, ensuring the `contract_address`, `receiver_id`, and `amount` matches the `mint`'s function arguments). 
3. Click the "clone card" tab. Apart from noticing that "Invalid JSON" or "Invalid Address" comes up unexpectedly, the DAO address that we entered earlier might get missing in this step. 
4. Go to **Export** tab and try increase `attached deposit` and `gas` to max, changing name of "Proposal Description". 
5. The "Propose On" button stays disabled; 
6. (To solve, add back the DAO address)

**Expected behavior**
Assuming the "total attached deposit" exceeded the "attached deposit" of each individual cards; button "Propose on" should be enabled. 

**Screenshots**
![image](https://user-images.githubusercontent.com/71509699/167991274-1713069a-de92-4011-8f34-29e1863189b2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version 1.38.111

**Smartphone (please complete the following information):**
(N/A)

**Additional context**
It's really the **DAO address not saved** that's causing the problem. We really need a cache/cookies to save that DAO address!

**Comment by lennczar** [comment]
**Thank you for the feedback, we will further discuss it here:**
- [duplicate] #5 
- #94, #95
