### ISSUE TITLE
Multicall Beta Test

### ISSUE THREAD

**Issue by tructhy1719** [near-multicall/ui#91]
**Discord or Telegram handle**  
Telegram: @sonatruc

**Testnet DAO address**  
Testnet DAO address(es) used during the test: sancho-learnnear-dao.sputnikv2.testnet

**what did you like the most?**  
- Best tool serves DAOs.
- UX (Create proposals with multicall) very good and modern (drag & drop).

**What did you like least?**  
- Very difficult to distinguish if there are many columns
<img width="550" alt="Screen Shot 2022-05-12 at 10 56 55" src="https://user-images.githubusercontent.com/105408698/168002954-a58fe350-68a4-4258-8d0a-02e2f0dc8de4.png">

- Very hard for know card select and edit. Should make high light card selected
<img width="553" alt="Screen Shot 2022-05-12 at 13 08 15" src="https://user-images.githubusercontent.com/105408698/168003401-23d4d97b-ad83-4b79-990a-b847cb4b318b.png">

- Should have alert confirm when user delete card or column. Because icon delete and clone very near.
- Didn't have notification status when search and create proposals.
- Didn't have page for user. Very confused when click user name for sign out

**What was the most difficult?**  
- Must read document for get value some fields input when create proposals.
- Very hard for non developer or crypto understand unit of gas and deposit. Should add tooltip explain its.

**What did you find easy?**  
- Have cards template in tab build.

**On a scale from 1 to 5 (1 = not good, 5 = really good)**  
* The instructions on DAO setup were easy to follow: 5
* The instructions on multicalls usage were easy to follow: 5

**finally, do you have some other thoughts you'd like to share?**  
- I created bug validate Function arguments when have multiple card on form https://airtable.com/. But may be i give wrong telegram account by discord. Here is correct infor: Telegram: @sonatruc

**Comment by lennczar** [comment]
**Thank you for the feedback, we will further discuss it here:**
- [duplicate] #88 
- [duplicate] #78 
- [duplicate] #81 
- [duplicate] #73 
- #95
